apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lut734-hs-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lut734-hs-dotnet-basic-gitops